### ISSUE TITLE
Error: Can't resolve 'crypto' --> in browser.js

### ISSUE THREAD

**Issue by rajrayala** [spurreiter/proof-of-login#1]
This issue occurred while running my Angular 7 application using 'npm run start'. I tried multiple ways to resolve, but none didn't worked.

Tried this:
https://stackoverflow.com/questions/66437032/node-modules-instagram-private-api-dist-repositories-request-js-crypto-could

**Comment by spurreiter** [comment]
@rajrayala This package does not require the node crypto library at all. It uses the crypto library from `window.crypto` for js/browser.js in such cases.
With your error message I can't give you any further info as the problem seams to be related to your project setup.
Please take a look at the example which shows you how you can use this library in the browser and backend.

**Comment by rajrayala** [comment]
I believe import('crypto') inside solver.js might be causing the issue.

I tried with both Angular 7 and Angular 13 Projects, none of them worked, it's throwing same error on compilation/ build. But for Angular 13 Project, when I used the suggestion provided in the above stackoverflow link, it worked.
